/**
 * Modo de agendamento canônico do domínio.
 * O adapter é responsável por mapear dos valores legados do banco:
 *   'ordem_chegada'  → 'capacity_window'
 *   'hora_marcada'   → 'time_slot'
 */
export type BookingMode = 'capacity_window' | 'time_slot';

export type PeriodKey = 'manha' | 'tarde';

export interface PeriodConfig {
  inicio: string;              // "07:00"
  fim: string;                 // "12:00"
  limite: number;
  dias_especificos?: number[]; // 0=dom … 6=sab
  distribuicao_fichas?: string;
}

export interface OrdemChegadaConfig {
  hora_chegada_inicio: string;
  hora_chegada_fim: string;
  hora_atendimento_inicio?: string;
  mensagem?: string;
}

// ─── Saída do use case (domínio neutro — sem formatação de canal) ────────────

export interface AvailableWindow {
  periodKey: PeriodKey;
  start: string;        // "07:00"
  end: string;          // "12:00"
  available: number;    // vagas disponíveis
  capacity: number;     // limite total
  bookingMode: BookingMode;
}

export interface AvailableDay {
  date: string;         // YYYY-MM-DD
  weekday: number;      // 0-6
  windows: AvailableWindow[];
}

// ─── BookAppointmentUseCase ───────────────────────────────────────────────────

export interface BookAppointmentPatient {
  nomeCompleto: string;   // already uppercased by adapter
  dataNascimento: string;
  convenio: string;       // already formatted by adapter
  celular: string;
  telefone?: string | null;
}

export interface BookAppointmentAppointment {
  medicoId: string;
  clienteId: string;
  atendimentoId: string;
  date: string;          // YYYY-MM-DD
  time: string;          // HH:MM:SS
  observacoes?: string;
}

export interface BookAppointmentMeta {
  criadoPor: string;
  criadoPorUserId?: string | null;
  /** Heuristic key generated by adapter: clienteId:celular:medicoId:date:time */
  idempotencyKey: string;
}

export interface BookAppointmentInput {
  patient: BookAppointmentPatient;
  appointment: BookAppointmentAppointment;
  meta: BookAppointmentMeta;
}

export interface BookAppointmentOutput {
  appointmentId: string;
  patientId: string;
  /** false when an existing record was returned (idempotent call) */
  created: boolean;
  /** Transitional: message from RPC, to be used by adapter for confirmation text */
  backendMessage?: string;
}

// ─── Domain errors ────────────────────────────────────────────────────────────

export class SlotAlreadyTakenError extends Error {
  readonly medicoId: string;
  readonly date: string;
  readonly time: string;

  constructor(params: { medicoId: string; date: string; time: string }) {
    super(`Slot already taken: ${params.medicoId}/${params.date}/${params.time}`);
    this.name = 'SlotAlreadyTakenError';
    this.medicoId = params.medicoId;
    this.date = params.date;
    this.time = params.time;
  }
}

export class DuplicateBookingError extends Error {
  constructor(
    public readonly appointmentId: string,
    public readonly patientId: string,
  ) {
    super(`Duplicate booking already exists: ${appointmentId}`);
    this.name = 'DuplicateBookingError';
  }
}

// ─── CancelAppointmentUseCase ─────────────────────────────────────────────────

/**
 * Status canônico do domínio.
 * O repository mapeia dos valores do banco:
 *   'agendado'   → 'booked'
 *   'confirmado' → 'confirmed'
 *   'cancelado'  → 'cancelled'
 */
export type AppointmentStatus = 'booked' | 'confirmed' | 'cancelled';

export interface AppointmentDetails {
  id: string;
  clienteId: string;
  medicoId: string;
  atendimentoId: string;
  pacienteId: string;
  date: string;      // YYYY-MM-DD
  time: string;      // HH:MM:SS
  status: AppointmentStatus;
  observacoes?: string;
}

export interface CancelAppointmentInput {
  appointmentId: string;
  clienteId: string;
  motivo?: string;
  canceladoPor: string;
}

export interface CancelAppointmentOutput {
  appointmentId: string;
  /** Status antes da transição — nunca 'cancelled' (use case rejeita esse caso) */
  previousStatus: 'booked' | 'confirmed';
}

export class AppointmentNotFoundError extends Error {
  constructor(public readonly appointmentId: string) {
    super(`Appointment not found: ${appointmentId}`);
    this.name = 'AppointmentNotFoundError';
  }
}

export class InvalidStatusTransitionError extends Error {
  constructor(public readonly currentStatus: AppointmentStatus) {
    super(`Cannot cancel appointment with status: ${currentStatus}`);
    this.name = 'InvalidStatusTransitionError';
  }
}
